name: CD NPM

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          registry-url: https://registry.npmjs.org
      - run: yarn --frozen-lockfile
      - run: yarn format
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: cp LICENSE lib/LICENSE
      - run: cp README.md lib/README.md
      - run: jq 'del(.devDependencies) | del(.scripts)' package.json > lib/package.json
      - run: npm publish ./lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
